CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_name UNIQUE (name),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE tags
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,

    CONSTRAINT pk_tags PRIMARY KEY (id),
    CONSTRAINT uk_tags_name UNIQUE (name)
);

CREATE TABLE posts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT                   NOT NULL,
    type         VARCHAR(255)             NOT NULL,
    content      VARCHAR(255),
    picture_path VARCHAR(255),
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_posts PRIMARY KEY (id),
    CONSTRAINT fk_posts_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_posts_type
        CHECK (type IN ('PICTURE', 'TEXT', 'PICTURE_WITH_TEXT'))
);

CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_id    BIGINT                      NOT NULL,
    user_id    BIGINT                      NOT NULL,
    content    VARCHAR(255)                NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comments_post
        FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_comments_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE post_tags
(
    post_id BIGINT NOT NULL,
    tag_id  BIGINT NOT NULL,

    CONSTRAINT pk_post_tags PRIMARY KEY (post_id, tag_id),
    CONSTRAINT fk_post_tags_post
        FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_post_tags_tag
        FOREIGN KEY (tag_id) REFERENCES tags (id)
);